version: 2.1

parameters:
 repo:
   type: string
   default: ""
 docker-image:
   type: string
   default: ""
 target:
   type: string
   default: ""

# example workflow that simulates a custom build process
jobs:
  deploy:
    docker:
      - image: cimg/ruby:2.4-node
    steps:
      - checkout
      - run: echo "hello world"
      - run: echo "Cloning << pipeline.parameters.repo >>"
      - run: echo "builder docker image << pipeline.parameters.docker-image >> from repo: << pipeline.parameters.repo >>"
      - run: echo "Deploying to << pipeline.parameters.target >>"
      - run: echo "insert calling aws apis to create ecs instance here..."
      - run: echo "Waiting for deploy..."
workflows:
  deploy:
   jobs:
     - deploy
