version: 2.1

parameters:
 repo:
   type: string
 docker-image:
   type: string
 target:
   type: string

# example workflow that simulates a custom build process
jobs:
  deploy:
    docker:
      - image: cimg/ruby:2.4-node
    steps:
      - checkout
      - run: echo "Cloning << parameters.repo >>"
      - run: echo "builder docker image << parameters.docker-image >> from repo: << parameters.repo >>"
      - run: echo "Deploying to << parameters.target >>"
      - run: echo "insert calling aws apis to create ecs instance here..."
      - run: echo "Waiting for deploy..."
workflows:
  deploy:
    - deploy
