version: 2.1

jobs:
  build:
    docker:
      - image: cimg/ruby:2.4-node
      - image: cimg/postgres:9.4.12
    steps:
      - checkout
      - run: yarn build
  test:
    docker:
      - image: cimg/ruby:2.4-node
      - image: cimg/postgres:9.4.12
    steps:
      - checkout
      - run: yarn test
  deploy:
    docker:
      - image: cimg/ruby:2.4-node
      - image: cimg/postgres:9.4.12
    steps:
      - checkout
      # this ends up running our deploy.yaml in the `deploys` folder of the repo
      - circleci/deploy
          name: platform-deploy-workflow
          repo: my-repo
          docker-image: my-docker-image
          target: aws-ecs
workflows:
  build_test_deploy:
    jobs:
      - build
      - test
      - deploy:
          filters:
            branches:
              only:
                - main
          requires:
            - build
            - test
          
